security:
    providers:
        user_provider:
            # Loads user from user repository
            entity:
                class: App\Entity\User
                property: username
        
        in_memory:
            memory:
                users:
                    '%env(resolve:API_USER)%':
                        password: '%env(resolve:API_PASS)%'
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
                    
    firewalls:
        api:
            pattern: /api
            http_basic: ~
            provider: in_memory
            anonymous: true
            
        app:
            pattern:    ^/
            provider: user_provider
            anonymous: true
            saml:
                # Match SAML attribute 'uid' with username.
                username_attribute: uid
                # Use the attribute's friendlyName instead of the name 
                use_attribute_friendly_name: false
                
                check_path: /saml/acs
                login_path: /saml/login
            
            logout:
                path: /saml/logout

    access_control:
        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_ADMIN }
        - { path: ^/event/feed, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        



