app_dashboard:
    path: /
    controller: App\Controller\DashboardController::homepage

# ---People--- #
app_people:
    path: /people
    controller: App\Controller\PeopleController::list

app_person_create:
    path: /person/create
    controller: App\Controller\PeopleController::new
     
app_person:
    path: /person/{id}
    controller: App\Controller\PeopleController::show
    
app_person_edit:
    path: /person/{id}/edit
    controller: App\Controller\PeopleController::edit
    
app_person_delete:
    path: /person/{id}/delete
    controller: App\Controller\PeopleController::delete


# Person - Memberships:
app_person_membership:
    path: /person/{id}/membership
    controller: App\Controller\PeopleController::show

app_person_membership_create:
    path: /person/{id}/membership/create
    controller: App\Controller\MembershipController::new
    
app_person_membership_edit:
    path: /person/{id}/membership/{membershipID}/edit
    controller: App\Controller\MembershipController::edit
    
app_person_membership_delete:
    path: /person/{id}/membership/{membershipID}/delete
    controller: App\Controller\MembershipController::delete


# Person - MusicalInstrument:
app_person_musicalInstrument:
    path: /person/{id}/musical-instrument
    controller: App\Controller\PeopleController::show
    
app_person_musicalInstrument_create:
    path: /person/{id}/musical-instrument/create
    controller: App\Controller\MusicalInstrumentController::edit

app_person_musicalInstrument_edit:
    path: /person/{id}/musical-instrument/edit
    controller: App\Controller\MusicalInstrumentController::edit

app_person_musicalInstrument_delete:
    path: /person/{id}/musical-instrument/delete
    controller: App\Controller\MusicalInstrumentController::delete


# Person - Education:
app_person_education:
    path: /person/{id}/education
    controller: App\Controller\PeopleController::show

app_person_education_create:
    path: /person/{id}/education/create
    controller: App\Controller\EducationController::new
    
app_person_education_edit:
    path: /person/{id}/education/{educationID}/edit
    controller: App\Controller\EducationController::edit
    
app_person_education_delete:
    path: /person/{id}/education/{educationID}/delete
    controller: App\Controller\EducationController::delete


# Person - memberOf:
app_person_memberOf:
    path: /person/{id}/memberof
    controller: App\Controller\PeopleController::show

app_person_memberOf_create:
    path: /person/{id}/memberof/create
    controller: App\Controller\MemberOfController::edit
    
app_person_memberOf_edit:
    path: /person/{id}/memberof/edit
    controller: App\Controller\MemberOfController::edit
    

# Person - Products:


# Person - Services:


# Person - Reviews:
app_person_review:
    path: /person/{id}/review
    controller: App\Controller\PeopleController::list

app_review_create_person:
    path: /person/{id}/review/create
    controller: App\Controller\ReviewController::newPersonReview

app_review_edit:
    path: /{entity}/{entityID}/review/{reviewID}/edit
    controller: App\Controller\ReviewController::editReview

app_review_delete:
    path: /{entity}/{entityID}/review/{reviewID}/delete
    controller: App\Controller\ReviewController::deleteReview


# ---Organizations--- #
app_organizations:
    path: /organizations
    controller: App\Controller\OrganizationsController::list

app_organization_create:
    path: /organization/create
    controller: App\Controller\OrganizationsController::new
     
app_organization:
    path: /organization/{id}
    controller: App\Controller\OrganizationsController::show
    
app_organization_edit:
    path: /organization/{id}/edit
    controller: App\Controller\OrganizationsController::edit
    
app_organization_delete:
    path: /organization/{id}/delete
    controller: App\Controller\OrganizationsController::delete











app_events:
    path: /events
    controller: App\Controller\EventsController::list

app_products:
    path: /products
    controller: App\Controller\ProductsController::list

app_services:
    path: /services
    controller: App\Controller\ServicesController::list


# ---Categories--- #
app_settings_categories:
    path: /settings/categories
    controller: App\Controller\CategoriesController::list

app_settings_categorie_create:
    path: /settings/categorie/create
    controller: App\Controller\CategoriesController::new
    
app_settings_categorie_edit:
    path: /settings/categorie/{id}/edit
    controller: App\Controller\CategoriesController::edit

app_settings_categorie_delete:
    path: /settings/categorie/{id}/delete
    controller: App\Controller\CategoriesController::show

# ---ProgramMemberships--- #
app_settings_program_memberships:
    path: /settings/programmemberships
    controller: App\Controller\ProgramMembershipController::list

app_settings_program_membership_create:
    path: /settings/programmembership/create
    controller: App\Controller\ProgramMembershipController::new
    
app_settings_program_membership_edit:
    path: /settings/programmembership/{id}/edit
    controller: App\Controller\ProgramMembershipController::edit
    
app_settings_program_membership_delete:
    path: /settings/programmembership/{id}/delete
    controller: App\Controller\ProgramMembershipController::delete

# ---MusicalInstruments--- #
app_settings_musical_instruments:
    path: /settings/musicalinstruments
    controller: App\Controller\MusicalInstrumentsController::list
    
app_settings_app_settings_musical_instrument_create:
    path: /settings/musicalinstrument/create
    controller: App\Controller\MusicalInstrumentsController::new
    
app_settings_program_settings_musical_instrument_edit:
    path: /settings/musicalinstrument/{id}/edit
    controller: App\Controller\MusicalInstrumentsController::edit
    
app_settings_program_settings_musical_instrument_delete:
    path: /settings/musicalinstrument/{id}/delete
    controller: App\Controller\MusicalInstrumentsController::delete