app_dashboard:
    path: /
    controller: App\Controller\DashboardController::homepage


# ---People--- #
app_people:
    path: /people
    controller: App\Controller\PeopleController::list

app_person_create:
    path: /person/create
    controller: App\Controller\PeopleController::new
     
app_person:
    path: /person/{id}
    controller: App\Controller\PeopleController::show
    
app_person_edit:
    path: /person/{id}/edit
    controller: App\Controller\PeopleController::edit
    
app_person_delete:
    path: /person/{id}/delete
    controller: App\Controller\PeopleController::delete


# Person - Parents:
app_person_parents:
    path: /person/{id}/parents
    controller: App\Controller\PeopleController::show
    
app_person_parents_create:
    path: /person/{id}/parents/create
    controller: App\Controller\ParentsController::edit

app_person_parents_edit:
    path: /person/{id}/parents/edit
    controller: App\Controller\ParentsController::edit
    

# Person - Memberships:
app_person_membership:
    path: /person/{id}/membership
    controller: App\Controller\PeopleController::show

app_person_membership_create:
    path: /person/{id}/membership/create
    controller: App\Controller\MembershipController::new
    
app_person_membership_edit:
    path: /person/{id}/membership/{membershipID}/edit
    controller: App\Controller\MembershipController::edit
    
app_person_membership_delete:
    path: /person/{id}/membership/{membershipID}/delete
    controller: App\Controller\MembershipController::delete


# Person - MusicalInstrument:
app_person_musicalInstrument:
    path: /person/{id}/musical-instrument
    controller: App\Controller\PeopleController::show
    
app_person_musicalInstrument_create:
    path: /person/{id}/musical-instrument/create
    controller: App\Controller\MusicalInstrumentController::edit

app_person_musicalInstrument_edit:
    path: /person/{id}/musical-instrument/edit
    controller: App\Controller\MusicalInstrumentController::edit


# Person - Education:
app_person_education:
    path: /person/{id}/education
    controller: App\Controller\PeopleController::show

app_person_education_create:
    path: /person/{id}/education/create
    controller: App\Controller\EducationController::new
    
app_person_education_edit:
    path: /person/{id}/education/{educationID}/edit
    controller: App\Controller\EducationController::edit
    
app_person_education_delete:
    path: /person/{id}/education/{educationID}/delete
    controller: App\Controller\EducationController::delete


# Person - memberOf:
app_person_memberOf:
    path: /person/{id}/memberof
    controller: App\Controller\PeopleController::show

app_person_memberOf_create:
    path: /person/{id}/memberof/create
    controller: App\Controller\MemberOfController::edit
    
app_person_memberOf_edit:
    path: /person/{id}/memberof/edit
    controller: App\Controller\MemberOfController::edit
 

# ---Organizations--- #
app_organizations:
    path: /organizations
    controller: App\Controller\OrganizationsController::list

app_organization_create:
    path: /organization/create
    controller: App\Controller\OrganizationsController::new
     
app_organization:
    path: /organization/{id}
    controller: App\Controller\OrganizationsController::show
    
app_organization_edit:
    path: /organization/{id}/edit
    controller: App\Controller\OrganizationsController::edit
    
app_organization_delete:
    path: /organization/{id}/delete
    controller: App\Controller\OrganizationsController::delete


# Organization - employee:
app_organization_employee:
    path: /organization/{id}/employee
    controller: App\Controller\OrganizationsController::show

app_organization_employee_create:
    path: /organization/{id}/employee/create
    controller: App\Controller\EmployeeController::edit
    
app_organization_employee_edit:
    path: /organization/{id}/employee/edit
    controller: App\Controller\EmployeeController::edit
    

# ---products--- #
app_products:
    path: /products
    controller: App\Controller\ProductsController::list

app_product_create:
    path: /product/create
    controller: App\Controller\ProductsController::new
     
app_product:
    path: /product/{id}
    controller: App\Controller\ProductsController::show
    
app_product_edit:
    path: /product/{id}/edit
    controller: App\Controller\ProductsController::edit
    
app_product_delete:
    path: /product/{id}/delete
    controller: App\Controller\ProductsController::delete


# Products - isRelatedTo:
app_product_isRelatedTo:
    path: /product/{id}/isrelatedto
    controller: App\Controller\ProductsController::show

app_product_isRelatedTo_edit:
    path: /product/{id}/isrelatedto/edit
    controller: App\Controller\ProductRelatedToController::edit


# ---Events--- #
app_events:
    path: /events
    controller: App\Controller\EventsController::list


# ---Services--- #
app_services:
    path: /services
    controller: App\Controller\ServicesController::list

app_service_create:
    path: /service/create
    controller: App\Controller\ServicesController::new
    
app_service:
    path: /service/{id}
    controller: App\Controller\ServicesController::show
    
app_service_edit:
    path: /service/{id}/edit
    controller: App\Controller\ServicesController::edit
    
app_service_delete:
    path: /service/{id}/delete
    controller: App\Controller\ServicesController::delete
    

# ---Offer--- #
app_service_offer:
    path: /service/{id}/offer
    controller: App\Controller\ServicesController::show
    
app_offer_create:
    path: /service/{id}/offer/create
    controller: App\Controller\OffersController::new
    
app_offer_edit:
    path: /service/{id}/offer/{offerID}/edit
    controller: App\Controller\OffersController::edit 
    
app_offer_delete:
    path: /service/{id}/offer/{offerID}/delete
    controller: App\Controller\OffersController::delete       


# ---Categories--- #
app_settings_categories:
    path: /settings/categories
    controller: App\Controller\CategoriesController::list

app_settings_categorie_create:
    path: /settings/categorie/create
    controller: App\Controller\CategoriesController::new
    
app_settings_categorie_edit:
    path: /settings/categorie/{id}/edit
    controller: App\Controller\CategoriesController::edit

app_settings_categorie_delete:
    path: /settings/categorie/{id}/delete
    controller: App\Controller\CategoriesController::show


# ---ProgramMemberships--- #
app_settings_program_memberships:
    path: /settings/programmemberships
    controller: App\Controller\ProgramMembershipController::list

app_settings_program_membership_create:
    path: /settings/programmembership/create
    controller: App\Controller\ProgramMembershipController::new
    
app_settings_program_membership_edit:
    path: /settings/programmembership/{id}/edit
    controller: App\Controller\ProgramMembershipController::edit
    
app_settings_program_membership_delete:
    path: /settings/programmembership/{id}/delete
    controller: App\Controller\ProgramMembershipController::delete


# ---MusicalInstruments--- #
app_settings_musical_instruments:
    path: /settings/musicalinstruments
    controller: App\Controller\MusicalInstrumentsController::list
    
app_settings_app_settings_musical_instrument_create:
    path: /settings/musicalinstrument/create
    controller: App\Controller\MusicalInstrumentsController::new
    
app_settings_program_settings_musical_instrument_edit:
    path: /settings/musicalinstrument/{id}/edit
    controller: App\Controller\MusicalInstrumentsController::edit
    
app_settings_program_settings_musical_instrument_delete:
    path: /settings/musicalinstrument/{id}/delete
    controller: App\Controller\MusicalInstrumentsController::delete

    
# ---Reviews--- #
app_review_create:
    path: /{entity}/{id}/review/create
    controller: App\Controller\ReviewController::new

app_review_edit:
    path: /{entity}/{id}/review/{reviewID}/edit
    controller: App\Controller\ReviewController::edit

app_review_delete:
    path: /{entity}/{id}/review/{reviewID}/delete
    controller: App\Controller\ReviewController::delete
    

# ---Owns--- #
app_person_owns:
    path: /person/{id}/owns
    controller: App\Controller\PeopleController::show
    
app_organization_owns:
    path: /organization/{id}/owns
    controller: App\Controller\OrganizationsController::show

app_owns_create:
    path: /{entity}/{id}/owns/create
    controller: App\Controller\OwnsController::new
    
app_owns_edit:
    path: /{entity}/{id}/owns/{ownershipInfoID}/edit
    controller: App\Controller\OwnsController::edit
    
app_owns_delete:
    path: /{entity}/{id}/owns/{ownershipInfoID}/delete
    controller: App\Controller\OwnsController::delete 
    

# ---Orders--- #
app_person_customer:
    path: /person/{id}/customer
    controller: App\Controller\PeopleController::show

app_orders:
    path: /orders
    controller: App\Controller\OrderController::list

app_order_create:
    path: /{entity}/{id}/order/create
    controller: App\Controller\OrderController::new
    
app_order:
    path: /{entity}/{id}/order/{orderID}
    controller: App\Controller\OrderController::show
    
app_order_edit:
    path: /{entity}/{id}/order/{orderID}/edit
    controller: App\Controller\OrderController::edit 
    
app_order_delete:
    path: /{entity}/{id}/order/{orderID}/delete
    controller: App\Controller\OrderController::delete 
