<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181214201738 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, about LONGTEXT NOT NULL, description LONGTEXT DEFAULT NULL, start_date DATETIME DEFAULT NULL, end_date DATETIME DEFAULT NULL, door_time DATETIME DEFAULT NULL, event_status LONGTEXT DEFAULT NULL, maximum_attendee_capacity LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_postal_address (event_id INT NOT NULL, postal_address_id INT NOT NULL, INDEX IDX_486A4D8471F7E88B (event_id), INDEX IDX_486A4D84FD54954B (postal_address_id), PRIMARY KEY(event_id, postal_address_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_attendee (event_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_57BC3CB771F7E88B (event_id), INDEX IDX_57BC3CB7217BBB47 (person_id), PRIMARY KEY(event_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_organizer (event_id INT NOT NULL, organization_id INT NOT NULL, INDEX IDX_1F414F4E71F7E88B (event_id), INDEX IDX_1F414F4E32C8A3DE (organization_id), PRIMARY KEY(event_id, organization_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_performer (event_id INT NOT NULL, organization_id INT NOT NULL, INDEX IDX_91B435D671F7E88B (event_id), INDEX IDX_91B435D632C8A3DE (organization_id), PRIMARY KEY(event_id, organization_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_contributor (event_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_71E6441371F7E88B (event_id), INDEX IDX_71E64413217BBB47 (person_id), PRIMARY KEY(event_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_event (event_source INT NOT NULL, event_target INT NOT NULL, INDEX IDX_7AB5BB8B6D130821 (event_source), INDEX IDX_7AB5BB8B74F658AE (event_target), PRIMARY KEY(event_source, event_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_sponsor (event_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_4DB607B71F7E88B (event_id), INDEX IDX_4DB607B217BBB47 (person_id), PRIMARY KEY(event_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_categorie (event_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_CFE8E80971F7E88B (event_id), INDEX IDX_CFE8E809BCF5E72D (categorie_id), PRIMARY KEY(event_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_review (event_id INT NOT NULL, review_id INT NOT NULL, INDEX IDX_4BDAF69471F7E88B (event_id), INDEX IDX_4BDAF6943E2E969B (review_id), PRIMARY KEY(event_id, review_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, description LONGTEXT DEFAULT NULL, product_id LONGTEXT DEFAULT NULL, model LONGTEXT DEFAULT NULL, manufacturer LONGTEXT DEFAULT NULL, purchase_date DATE DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_review (product_id INT NOT NULL, review_id INT NOT NULL, INDEX IDX_1B3FC0624584665A (product_id), INDEX IDX_1B3FC0623E2E969B (review_id), PRIMARY KEY(product_id, review_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_product (product_source INT NOT NULL, product_target INT NOT NULL, INDEX IDX_2931F1D3DF63ED7 (product_source), INDEX IDX_2931F1D24136E58 (product_target), PRIMARY KEY(product_source, product_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_categorie (product_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_27DD60B94584665A (product_id), INDEX IDX_27DD60B9BCF5E72D (categorie_id), PRIMARY KEY(product_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE review (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, review_aspect LONGTEXT NOT NULL, review_body LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_794381C6F675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, service_type LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_organization (service_id INT NOT NULL, organization_id INT NOT NULL, INDEX IDX_1E421699ED5CA9E6 (service_id), INDEX IDX_1E42169932C8A3DE (organization_id), PRIMARY KEY(service_id, organization_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_review (service_id INT NOT NULL, review_id INT NOT NULL, INDEX IDX_478484F0ED5CA9E6 (service_id), INDEX IDX_478484F03E2E969B (review_id), PRIMARY KEY(service_id, review_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_isRelatedTo (service_source INT NOT NULL, service_target INT NOT NULL, INDEX IDX_9645FA7C614D7A45 (service_source), INDEX IDX_9645FA7C78A82ACA (service_target), PRIMARY KEY(service_source, service_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_categorie (service_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_11ECEC7EED5CA9E6 (service_id), INDEX IDX_11ECEC7EBCF5E72D (categorie_id), PRIMARY KEY(service_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, family_name LONGTEXT DEFAULT NULL, given_name LONGTEXT NOT NULL, additional_name LONGTEXT DEFAULT NULL, birth_date DATE DEFAULT NULL, gender LONGTEXT DEFAULT NULL, email LONGTEXT DEFAULT NULL, telephone LONGTEXT DEFAULT NULL, mobile_phone LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_postal_address (person_id INT NOT NULL, postal_address_id INT NOT NULL, INDEX IDX_72F3CBC9217BBB47 (person_id), INDEX IDX_72F3CBC9FD54954B (postal_address_id), PRIMARY KEY(person_id, postal_address_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Person_knows (person_source INT NOT NULL, person_target INT NOT NULL, INDEX IDX_ADC7B6E7C32F4FC5 (person_source), INDEX IDX_ADC7B6E7DACA1F4A (person_target), PRIMARY KEY(person_source, person_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Person_parents (person_source INT NOT NULL, person_target INT NOT NULL, INDEX IDX_12AAD63BC32F4FC5 (person_source), INDEX IDX_12AAD63BDACA1F4A (person_target), PRIMARY KEY(person_source, person_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_musical_instrument (person_id INT NOT NULL, musical_instrument_id INT NOT NULL, INDEX IDX_CB18D820217BBB47 (person_id), INDEX IDX_CB18D8206863871A (musical_instrument_id), PRIMARY KEY(person_id, musical_instrument_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_education (person_id INT NOT NULL, education_id INT NOT NULL, INDEX IDX_6323BD78217BBB47 (person_id), INDEX IDX_6323BD782CA1BD71 (education_id), PRIMARY KEY(person_id, education_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_categorie (person_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_F154359E217BBB47 (person_id), INDEX IDX_F154359EBCF5E72D (categorie_id), PRIMARY KEY(person_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_program_membership (person_id INT NOT NULL, program_membership_id INT NOT NULL, INDEX IDX_40ACE896217BBB47 (person_id), INDEX IDX_40ACE896BAFA4455 (program_membership_id), PRIMARY KEY(person_id, program_membership_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_ownership_info (person_id INT NOT NULL, ownership_info_id INT NOT NULL, INDEX IDX_B4562E8B217BBB47 (person_id), INDEX IDX_B4562E8BBFF9CED (ownership_info_id), PRIMARY KEY(person_id, ownership_info_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_review (person_id INT NOT NULL, review_id INT NOT NULL, INDEX IDX_E5E6B170217BBB47 (person_id), INDEX IDX_E5E6B1703E2E969B (review_id), PRIMARY KEY(person_id, review_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE postal_address (id INT AUTO_INCREMENT NOT NULL, address_country LONGTEXT DEFAULT NULL, address_locality LONGTEXT DEFAULT NULL, post_office_box_number LONGTEXT DEFAULT NULL, postal_code LONGTEXT DEFAULT NULL, street_address LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ownership_info (id INT AUTO_INCREMENT NOT NULL, acquired_from_id INT DEFAULT NULL, owned_from DATETIME DEFAULT NULL, owned_through DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_518B1EB5B43AA055 (acquired_from_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ownership_info_product (ownership_info_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_7FF1D8E0BFF9CED (ownership_info_id), INDEX IDX_7FF1D8E04584665A (product_id), PRIMARY KEY(ownership_info_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ownership_info_categorie (ownership_info_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_83CFD538BFF9CED (ownership_info_id), INDEX IDX_83CFD538BCF5E72D (categorie_id), PRIMARY KEY(ownership_info_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE education (id INT AUTO_INCREMENT NOT NULL, certificate LONGTEXT NOT NULL, date_achieved DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE education_organization (education_id INT NOT NULL, organization_id INT NOT NULL, INDEX IDX_C21D03D02CA1BD71 (education_id), INDEX IDX_C21D03D032C8A3DE (organization_id), PRIMARY KEY(education_id, organization_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization (id INT AUTO_INCREMENT NOT NULL, legal_name LONGTEXT NOT NULL, description LONGTEXT DEFAULT NULL, email LONGTEXT DEFAULT NULL, telephone LONGTEXT DEFAULT NULL, mobile_phone LONGTEXT NOT NULL, lei_code LONGTEXT DEFAULT NULL, vat_id LONGTEXT DEFAULT NULL, url LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_postal_address (organization_id INT NOT NULL, postal_address_id INT NOT NULL, INDEX IDX_673C184432C8A3DE (organization_id), INDEX IDX_673C1844FD54954B (postal_address_id), PRIMARY KEY(organization_id, postal_address_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_person (organization_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_3152018332C8A3DE (organization_id), INDEX IDX_31520183217BBB47 (person_id), PRIMARY KEY(organization_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_ownership_info (organization_id INT NOT NULL, ownership_info_id INT NOT NULL, INDEX IDX_A199FD0632C8A3DE (organization_id), INDEX IDX_A199FD06BFF9CED (ownership_info_id), PRIMARY KEY(organization_id, ownership_info_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_review (organization_id INT NOT NULL, review_id INT NOT NULL, INDEX IDX_7CCD513332C8A3DE (organization_id), INDEX IDX_7CCD51333E2E969B (review_id), PRIMARY KEY(organization_id, review_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_categorie (organization_id INT NOT NULL, categorie_id INT NOT NULL, INDEX IDX_714A0C3232C8A3DE (organization_id), INDEX IDX_714A0C32BCF5E72D (categorie_id), PRIMARY KEY(organization_id, categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE event_postal_address ADD CONSTRAINT FK_486A4D8471F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_postal_address ADD CONSTRAINT FK_486A4D84FD54954B FOREIGN KEY (postal_address_id) REFERENCES postal_address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_attendee ADD CONSTRAINT FK_57BC3CB771F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_attendee ADD CONSTRAINT FK_57BC3CB7217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_organizer ADD CONSTRAINT FK_1F414F4E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_organizer ADD CONSTRAINT FK_1F414F4E32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_performer ADD CONSTRAINT FK_91B435D671F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_performer ADD CONSTRAINT FK_91B435D632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_contributor ADD CONSTRAINT FK_71E6441371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_contributor ADD CONSTRAINT FK_71E64413217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_event ADD CONSTRAINT FK_7AB5BB8B6D130821 FOREIGN KEY (event_source) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_event ADD CONSTRAINT FK_7AB5BB8B74F658AE FOREIGN KEY (event_target) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_sponsor ADD CONSTRAINT FK_4DB607B71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_sponsor ADD CONSTRAINT FK_4DB607B217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_categorie ADD CONSTRAINT FK_CFE8E80971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_categorie ADD CONSTRAINT FK_CFE8E809BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_review ADD CONSTRAINT FK_4BDAF69471F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_review ADD CONSTRAINT FK_4BDAF6943E2E969B FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC0624584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC0623E2E969B FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product ADD CONSTRAINT FK_2931F1D3DF63ED7 FOREIGN KEY (product_source) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_product ADD CONSTRAINT FK_2931F1D24136E58 FOREIGN KEY (product_target) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_categorie ADD CONSTRAINT FK_27DD60B94584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_categorie ADD CONSTRAINT FK_27DD60B9BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE service_organization ADD CONSTRAINT FK_1E421699ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_organization ADD CONSTRAINT FK_1E42169932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_review ADD CONSTRAINT FK_478484F0ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_review ADD CONSTRAINT FK_478484F03E2E969B FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_isRelatedTo ADD CONSTRAINT FK_9645FA7C614D7A45 FOREIGN KEY (service_source) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_isRelatedTo ADD CONSTRAINT FK_9645FA7C78A82ACA FOREIGN KEY (service_target) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_categorie ADD CONSTRAINT FK_11ECEC7EED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_categorie ADD CONSTRAINT FK_11ECEC7EBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_postal_address ADD CONSTRAINT FK_72F3CBC9217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_postal_address ADD CONSTRAINT FK_72F3CBC9FD54954B FOREIGN KEY (postal_address_id) REFERENCES postal_address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Person_knows ADD CONSTRAINT FK_ADC7B6E7C32F4FC5 FOREIGN KEY (person_source) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Person_knows ADD CONSTRAINT FK_ADC7B6E7DACA1F4A FOREIGN KEY (person_target) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Person_parents ADD CONSTRAINT FK_12AAD63BC32F4FC5 FOREIGN KEY (person_source) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Person_parents ADD CONSTRAINT FK_12AAD63BDACA1F4A FOREIGN KEY (person_target) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_musical_instrument ADD CONSTRAINT FK_CB18D820217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_musical_instrument ADD CONSTRAINT FK_CB18D8206863871A FOREIGN KEY (musical_instrument_id) REFERENCES musical_instrument (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_education ADD CONSTRAINT FK_6323BD78217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_education ADD CONSTRAINT FK_6323BD782CA1BD71 FOREIGN KEY (education_id) REFERENCES education (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_categorie ADD CONSTRAINT FK_F154359E217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_categorie ADD CONSTRAINT FK_F154359EBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_program_membership ADD CONSTRAINT FK_40ACE896217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_program_membership ADD CONSTRAINT FK_40ACE896BAFA4455 FOREIGN KEY (program_membership_id) REFERENCES program_membership (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_ownership_info ADD CONSTRAINT FK_B4562E8B217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_ownership_info ADD CONSTRAINT FK_B4562E8BBFF9CED FOREIGN KEY (ownership_info_id) REFERENCES ownership_info (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_review ADD CONSTRAINT FK_E5E6B170217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_review ADD CONSTRAINT FK_E5E6B1703E2E969B FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ownership_info ADD CONSTRAINT FK_518B1EB5B43AA055 FOREIGN KEY (acquired_from_id) REFERENCES organization (id)');
        $this->addSql('ALTER TABLE ownership_info_product ADD CONSTRAINT FK_7FF1D8E0BFF9CED FOREIGN KEY (ownership_info_id) REFERENCES ownership_info (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ownership_info_product ADD CONSTRAINT FK_7FF1D8E04584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ownership_info_categorie ADD CONSTRAINT FK_83CFD538BFF9CED FOREIGN KEY (ownership_info_id) REFERENCES ownership_info (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ownership_info_categorie ADD CONSTRAINT FK_83CFD538BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE education_organization ADD CONSTRAINT FK_C21D03D02CA1BD71 FOREIGN KEY (education_id) REFERENCES education (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE education_organization ADD CONSTRAINT FK_C21D03D032C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_postal_address ADD CONSTRAINT FK_673C184432C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_postal_address ADD CONSTRAINT FK_673C1844FD54954B FOREIGN KEY (postal_address_id) REFERENCES postal_address (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_person ADD CONSTRAINT FK_3152018332C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_person ADD CONSTRAINT FK_31520183217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_ownership_info ADD CONSTRAINT FK_A199FD0632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_ownership_info ADD CONSTRAINT FK_A199FD06BFF9CED FOREIGN KEY (ownership_info_id) REFERENCES ownership_info (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_review ADD CONSTRAINT FK_7CCD513332C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_review ADD CONSTRAINT FK_7CCD51333E2E969B FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_categorie ADD CONSTRAINT FK_714A0C3232C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organization_categorie ADD CONSTRAINT FK_714A0C32BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE event_postal_address DROP FOREIGN KEY FK_486A4D8471F7E88B');
        $this->addSql('ALTER TABLE event_attendee DROP FOREIGN KEY FK_57BC3CB771F7E88B');
        $this->addSql('ALTER TABLE event_organizer DROP FOREIGN KEY FK_1F414F4E71F7E88B');
        $this->addSql('ALTER TABLE event_performer DROP FOREIGN KEY FK_91B435D671F7E88B');
        $this->addSql('ALTER TABLE event_contributor DROP FOREIGN KEY FK_71E6441371F7E88B');
        $this->addSql('ALTER TABLE event_event DROP FOREIGN KEY FK_7AB5BB8B6D130821');
        $this->addSql('ALTER TABLE event_event DROP FOREIGN KEY FK_7AB5BB8B74F658AE');
        $this->addSql('ALTER TABLE event_sponsor DROP FOREIGN KEY FK_4DB607B71F7E88B');
        $this->addSql('ALTER TABLE event_categorie DROP FOREIGN KEY FK_CFE8E80971F7E88B');
        $this->addSql('ALTER TABLE event_review DROP FOREIGN KEY FK_4BDAF69471F7E88B');
        $this->addSql('ALTER TABLE product_review DROP FOREIGN KEY FK_1B3FC0624584665A');
        $this->addSql('ALTER TABLE product_product DROP FOREIGN KEY FK_2931F1D3DF63ED7');
        $this->addSql('ALTER TABLE product_product DROP FOREIGN KEY FK_2931F1D24136E58');
        $this->addSql('ALTER TABLE product_categorie DROP FOREIGN KEY FK_27DD60B94584665A');
        $this->addSql('ALTER TABLE ownership_info_product DROP FOREIGN KEY FK_7FF1D8E04584665A');
        $this->addSql('ALTER TABLE event_review DROP FOREIGN KEY FK_4BDAF6943E2E969B');
        $this->addSql('ALTER TABLE product_review DROP FOREIGN KEY FK_1B3FC0623E2E969B');
        $this->addSql('ALTER TABLE service_review DROP FOREIGN KEY FK_478484F03E2E969B');
        $this->addSql('ALTER TABLE person_review DROP FOREIGN KEY FK_E5E6B1703E2E969B');
        $this->addSql('ALTER TABLE organization_review DROP FOREIGN KEY FK_7CCD51333E2E969B');
        $this->addSql('ALTER TABLE service_organization DROP FOREIGN KEY FK_1E421699ED5CA9E6');
        $this->addSql('ALTER TABLE service_review DROP FOREIGN KEY FK_478484F0ED5CA9E6');
        $this->addSql('ALTER TABLE service_isRelatedTo DROP FOREIGN KEY FK_9645FA7C614D7A45');
        $this->addSql('ALTER TABLE service_isRelatedTo DROP FOREIGN KEY FK_9645FA7C78A82ACA');
        $this->addSql('ALTER TABLE service_categorie DROP FOREIGN KEY FK_11ECEC7EED5CA9E6');
        $this->addSql('ALTER TABLE event_attendee DROP FOREIGN KEY FK_57BC3CB7217BBB47');
        $this->addSql('ALTER TABLE event_contributor DROP FOREIGN KEY FK_71E64413217BBB47');
        $this->addSql('ALTER TABLE event_sponsor DROP FOREIGN KEY FK_4DB607B217BBB47');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE person_postal_address DROP FOREIGN KEY FK_72F3CBC9217BBB47');
        $this->addSql('ALTER TABLE Person_knows DROP FOREIGN KEY FK_ADC7B6E7C32F4FC5');
        $this->addSql('ALTER TABLE Person_knows DROP FOREIGN KEY FK_ADC7B6E7DACA1F4A');
        $this->addSql('ALTER TABLE Person_parents DROP FOREIGN KEY FK_12AAD63BC32F4FC5');
        $this->addSql('ALTER TABLE Person_parents DROP FOREIGN KEY FK_12AAD63BDACA1F4A');
        $this->addSql('ALTER TABLE person_musical_instrument DROP FOREIGN KEY FK_CB18D820217BBB47');
        $this->addSql('ALTER TABLE person_education DROP FOREIGN KEY FK_6323BD78217BBB47');
        $this->addSql('ALTER TABLE person_categorie DROP FOREIGN KEY FK_F154359E217BBB47');
        $this->addSql('ALTER TABLE person_program_membership DROP FOREIGN KEY FK_40ACE896217BBB47');
        $this->addSql('ALTER TABLE person_ownership_info DROP FOREIGN KEY FK_B4562E8B217BBB47');
        $this->addSql('ALTER TABLE person_review DROP FOREIGN KEY FK_E5E6B170217BBB47');
        $this->addSql('ALTER TABLE organization_person DROP FOREIGN KEY FK_31520183217BBB47');
        $this->addSql('ALTER TABLE event_postal_address DROP FOREIGN KEY FK_486A4D84FD54954B');
        $this->addSql('ALTER TABLE person_postal_address DROP FOREIGN KEY FK_72F3CBC9FD54954B');
        $this->addSql('ALTER TABLE organization_postal_address DROP FOREIGN KEY FK_673C1844FD54954B');
        $this->addSql('ALTER TABLE person_ownership_info DROP FOREIGN KEY FK_B4562E8BBFF9CED');
        $this->addSql('ALTER TABLE ownership_info_product DROP FOREIGN KEY FK_7FF1D8E0BFF9CED');
        $this->addSql('ALTER TABLE ownership_info_categorie DROP FOREIGN KEY FK_83CFD538BFF9CED');
        $this->addSql('ALTER TABLE organization_ownership_info DROP FOREIGN KEY FK_A199FD06BFF9CED');
        $this->addSql('ALTER TABLE person_education DROP FOREIGN KEY FK_6323BD782CA1BD71');
        $this->addSql('ALTER TABLE education_organization DROP FOREIGN KEY FK_C21D03D02CA1BD71');
        $this->addSql('ALTER TABLE event_organizer DROP FOREIGN KEY FK_1F414F4E32C8A3DE');
        $this->addSql('ALTER TABLE event_performer DROP FOREIGN KEY FK_91B435D632C8A3DE');
        $this->addSql('ALTER TABLE service_organization DROP FOREIGN KEY FK_1E42169932C8A3DE');
        $this->addSql('ALTER TABLE ownership_info DROP FOREIGN KEY FK_518B1EB5B43AA055');
        $this->addSql('ALTER TABLE education_organization DROP FOREIGN KEY FK_C21D03D032C8A3DE');
        $this->addSql('ALTER TABLE organization_postal_address DROP FOREIGN KEY FK_673C184432C8A3DE');
        $this->addSql('ALTER TABLE organization_person DROP FOREIGN KEY FK_3152018332C8A3DE');
        $this->addSql('ALTER TABLE organization_ownership_info DROP FOREIGN KEY FK_A199FD0632C8A3DE');
        $this->addSql('ALTER TABLE organization_review DROP FOREIGN KEY FK_7CCD513332C8A3DE');
        $this->addSql('ALTER TABLE organization_categorie DROP FOREIGN KEY FK_714A0C3232C8A3DE');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_postal_address');
        $this->addSql('DROP TABLE event_attendee');
        $this->addSql('DROP TABLE event_organizer');
        $this->addSql('DROP TABLE event_performer');
        $this->addSql('DROP TABLE event_contributor');
        $this->addSql('DROP TABLE event_event');
        $this->addSql('DROP TABLE event_sponsor');
        $this->addSql('DROP TABLE event_categorie');
        $this->addSql('DROP TABLE event_review');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_review');
        $this->addSql('DROP TABLE product_product');
        $this->addSql('DROP TABLE product_categorie');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_organization');
        $this->addSql('DROP TABLE service_review');
        $this->addSql('DROP TABLE service_isRelatedTo');
        $this->addSql('DROP TABLE service_categorie');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_postal_address');
        $this->addSql('DROP TABLE Person_knows');
        $this->addSql('DROP TABLE Person_parents');
        $this->addSql('DROP TABLE person_musical_instrument');
        $this->addSql('DROP TABLE person_education');
        $this->addSql('DROP TABLE person_categorie');
        $this->addSql('DROP TABLE person_program_membership');
        $this->addSql('DROP TABLE person_ownership_info');
        $this->addSql('DROP TABLE person_review');
        $this->addSql('DROP TABLE postal_address');
        $this->addSql('DROP TABLE ownership_info');
        $this->addSql('DROP TABLE ownership_info_product');
        $this->addSql('DROP TABLE ownership_info_categorie');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE education_organization');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_postal_address');
        $this->addSql('DROP TABLE organization_person');
        $this->addSql('DROP TABLE organization_ownership_info');
        $this->addSql('DROP TABLE organization_review');
        $this->addSql('DROP TABLE organization_categorie');
    }
}
